name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Get submodules
      run: git pull --recurse-submodules

    - name: Update
      run: sudo apt-get update --fix-missing
    
    - name: Install valgrind & tree
      run: sudo apt-get install valgrind tree

    - name: Install norminette
      run: pip install norminette

    - name: Run tree
      run: tree

    - name: Run norminette
      run: norminette philo philo_bonus
  
    - name: Make philosophers
      run: make PRETTY=false

    - name: Re-make philosophers
      run: make re PRETTY=false
    
    - name: View contents of philosophers
      run: nm -C philo/philo
    
    - name: View contents of philosophers bonus
      run: nm -C philo_bonus/philo_bonus
    
    - name: Run standard
      run: ./philo/philo 5 800 200 200 23
    
    - name: Run standard and check eat count of 1
      run: ./philo/philo 5 800 200 200 23 | grep "1 is eating" | wc -l
    
    - name: Run standard and check eat count of 2
      run: ./philo/philo 5 800 200 200 23 | grep "2 is eating" | wc -l

    - name: Run standard and check eat count of 3
      run: ./philo/philo 5 800 200 200 23 | grep "3 is eating" | wc -l

    - name: Run standard and check eat count of 4
      run: ./philo/philo 5 800 200 200 23 | grep "4 is eating" | wc -l

    - name: Run standard and check eat count of 5
      run: ./philo/philo 5 800 200 200 23 | grep "5 is eating" | wc -l

    - name: Run standard and check eat count of all
      run: ./philo/philo 5 800 200 200 23 | grep "is eating"| wc -l

    - name: Run standard with valgrind
      run: valgrind -s ./philo/philo 5 800 200 200 23
    
    - name: Run standard with valgrind with one die
      run: valgrind -s ./philo/philo 5 80 200 200 23
    
    - name: Run standard with valgrind with one
      run: valgrind -s ./philo/philo 1 800 200 200 23

    - name: Run standard with helgrind 
      run: valgrind --tool=helgrind -s ./philo/philo 10 800 200 200 23

    - name: Run standard with helgrind with one die
      run: valgrind --tool=helgrind -s ./philo/philo 1 80 200 200 23

    - name: Run standard with helgrind with one
      run: valgrind --tool=helgrind -s ./philo/philo 1 800 200 200 23

    - name: Run bonus
      run: ./philo_bonus/philo_bonus 5 800 200 200 23
    
    - name: Run bonus and check eat count of 1
      run: ./philo_bonus/philo_bonus 5 800 200 200 23 | grep "1 is eating" | wc -l
    
    - name: Run bonus and check eat count of 2
      run: ./philo_bonus/philo_bonus 5 800 200 200 23 | grep "2 is eating" | wc -l
    
    - name: Run bonus and check eat count of 3
      run: ./philo_bonus/philo_bonus 5 800 200 200 23 | grep "3 is eating" | wc -l

    - name: Run bonus and check eat count of 4
      run: ./philo_bonus/philo_bonus 5 800 200 200 23 | grep "4 is eating" | wc -l

    - name: Run bonus and check eat count of 5
      run: ./philo_bonus/philo_bonus 5 800 200 200 23 | grep "5 is eating" | wc -l

    - name: Run bonus and check eat count of all
      run: ./philo_bonus/philo_bonus 5 800 200 200 23 | grep "is eating"| wc -l

    - name: Run bonus with valgrind
      run: valgrind -s ./philo_bonus/philo_bonus 5 800 200 200 23

    - name: Run bonus with valgrind with one die
      run: valgrind -s ./philo_bonus/philo_bonus 5 80 200 200 23
    
    - name: Run bonus with valgrind with one
      run: valgrind -s ./philo_bonus/philo_bonus 1 800 200 200 23

    - name: Run bonus with helgrind
      run: valgrind --tool=helgrind -s ./philo_bonus/philo_bonus 10 800 200 200 23
    
    - name: Run bonus with helgrind with one die
      run: valgrind --tool=helgrind -s ./philo_bonus/philo_bonus 1 80 200 200 23

    - name: Run bonus with helgrind with one
      run: valgrind --tool=helgrind -s ./philo_bonus/philo_bonus 1 800 200 200 23
    
    - name: Test standard
      run: cd LazyPhilosophersTesterGithubActions && ./test.sh ../philo/philo
    
    - name: Test bonus
      run: cd LazyPhilosophersTesterGithubActions && ./test.sh ../philo_bonus/philo_bonus
