name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update
      run: sudo apt-get update --fix-missing
    
    - name: Install valgrind & tree
      run: sudo apt-get install valgrind tree

    - name: Install norminette
      run: pip install norminette

    - name: Run tree
      run: tree

    - name: Run norminette
      run: norminette philo philo_bonus
  
    - name: Make program
      run: make PRETTY=false

    - name: Re-make program
      run: make re PRETTY=false
    
    - name: Run standard
      run: ./philo/philo 5 800 200 200 20
    
    - name: Run standard and check eat count of 1
      run: ./philo/philo 5 800 200 200 7 | grep "1 is eating" | wc -l
    
    - name: Run standard and check eat count of all
      run: ./philo/philo 5 800 200 200 7 | grep "is eating"| wc -l

    - name: Run standard with valgrind
      run: valgrind -s ./philo/philo 5 8000000 200 200 20

    - name: Run standard with helgrind
      run: valgrind --tool=helgrind -s ./philo/philo 10 8000000 200 200 20
    
    - name: Run bonus
      run: ./philo_bonus/philo_bonus 5 800 200 200 20
    
    - name: Run bonus and check eat count of 1
      run: ./philo_bonus/philo_bonus 5 800 200 200 7 | grep "1 is eating" | wc -l
    
    - name: Run bonus and check eat count of all
      run: ./philo_bonus/philo_bonus 5 800 200 200 7 | grep "is eating"| wc -l

    - name: Run bonus with valgrind
      run: valgrind -s ./philo_bonus/philo_bonus 5 8000000 200 200 20

    - name: Run bonus with helgrind
      run: valgrind --tool=helgrind -s ./philo_bonus/philo_bonus 10 8000000 200 200 20
    
    - name: Clone tester
      run: git clone https://github.com/WOLFIE-OG/LazyPhilosophersTesterGithubActions
    
    - name: Test standard
      run: cd LazyPhilosophersTesterGithubActions && ./test.sh ../philo/philo
    
    - name: Test bonus
      run: cd LazyPhilosophersTesterGithubActions && ./test.sh ../philo_bonus/philo_bonus
