name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update
      run: sudo apt-get update --fix-missing
    
    - name: Get valgrind
      run: sudo apt-get install valgrind

    - name: Get norminette
      run: pip install norminette

    - name: Install tree
      run: sudo apt-get install tree

    - name: Tree
      run: tree

    - name: Run norminette
      run: norminette philo philo_bonus
  
    - name: Make program
      run: make

    - name: Re-make program
      run: make re
    
    - name: Run standard
      run: ./philo/philo 5 800 200 200 20

    - name: Run standard with valgrind
      run: valgrind -s ./philo/philo 5 8000000 200 200 20

    - name: Run standard with helgrind
      run: valgrind --tool=helgrind -s ./philo/philo 10 8000000 200 200 20
    
    - name: Run bonus
      run: ./philo_bonus/philo_bonus 5 800 200 200 20

    - name: Run bonus with valgrind
      run: valgrind -s ./philo_bonus/philo_bonus 5 8000000 200 200 20

    - name: Run bonus with helgrind
      run: valgrind --tool=helgrind -s ./philo_bonus/philo_bonus 10 8000000 200 200 20
