name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install tree
      run: sudo apt-get install tree

    - name: Tree
      run: tree
  
    - name: Make program
      run: make

    - name: Re-make program
      run: make re
